name: MT-YOLOv7-AOI
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - opencv>=4.1.2
  - pillow
  - pyyaml>=5.3.1
  - scipy>=1.4.1
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.6
  - tqdm>=4.41.0
  - tensorboard>=2.4.1
  - pandas
  - seaborn>=0.11.0
  - pycocotools>=2.0
#  - pip:
#    - thop
